# Generated by Django 4.1.5 on 2023-02-10 13:44

from django.db import migrations, models
import hesab.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('connections', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('body', models.TextField(default=hesab.models._secret)),
                ('info', models.TextField(blank=True, default='')),
            ],
        ),
    ]
