# Generated by Django 3.2 on 2023-08-02 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hesab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='secret',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hesab.secret'),
            preserve_default=False,
        ),
    ]
